/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.1.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TrendingHashtag {
    tag: string;
    count: bigint;
}
export type Time = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type PostType = {
    __kind__: "repost";
    repost: bigint;
} | {
    __kind__: "quote";
    quote: bigint;
} | {
    __kind__: "original";
    original: null;
} | {
    __kind__: "reply";
    reply: bigint;
};
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PaginatedPosts {
    hasMore: boolean;
    posts: Array<PostResponse>;
    nextCursor?: bigint;
}
export interface PaginatedNotifications {
    hasMore: boolean;
    notifications: Array<Notification>;
    nextCursor?: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfileResponse {
    bio: string;
    isBlockedByCurrentUser: boolean;
    principal: Principal;
    username: string;
    displayName: string;
    isMutedByCurrentUser: boolean;
    followersCount: bigint;
    createdAt: Time;
    updatedAt: Time;
    headerImageHash?: ExternalBlob;
    followingCount: bigint;
    isFollowedByCurrentUser: boolean;
    profilePictureHash?: ExternalBlob;
    postsCount: bigint;
}
export type NotificationType = {
    __kind__: "repost";
    repost: bigint;
} | {
    __kind__: "like";
    like: bigint;
} | {
    __kind__: "quote";
    quote: bigint;
} | {
    __kind__: "mention";
    mention: bigint;
} | {
    __kind__: "reply";
    reply: bigint;
} | {
    __kind__: "follow";
    follow: null;
};
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface FollowUserResponse {
    principal: Principal;
    username: string;
    displayName: string;
    profilePictureHash?: ExternalBlob;
}
export interface Notification {
    id: bigint;
    notificationType: NotificationType;
    createdAt: Time;
    isRead: boolean;
    actorUsername: string;
    actorPrincipal: Principal;
}
export interface PostResponse {
    id: bigint;
    postType: PostType;
    authorUsername: string;
    likeCount: bigint;
    isRepostedByCurrentUser: boolean;
    authorProfilePictureHash?: ExternalBlob;
    repostCount: bigint;
    createdAt: Time;
    text: string;
    author: Principal;
    mediaHash?: ExternalBlob;
    replyCount: bigint;
    mediaType?: string;
    editedAt?: Time;
    authorDisplayName: string;
    isLikedByCurrentUser: boolean;
}
export interface UserProfile {
    bio: string;
    username: string;
    displayName: string;
    createdAt: Time;
    updatedAt: Time;
    headerImageHash?: ExternalBlob;
    profilePictureHash?: ExternalBlob;
}
export interface PaginatedFollows {
    nextOffset?: bigint;
    hasMore: boolean;
    users: Array<FollowUserResponse>;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockUser(user: Principal): Promise<void>;
    checkUsernameAvailability(username: string): Promise<boolean>;
    createPost(text: string, mediaHash: ExternalBlob | null, mediaType: string | null): Promise<PostResponse>;
    createReply(parentPostId: bigint, text: string, mediaHash: ExternalBlob | null, mediaType: string | null): Promise<PostResponse>;
    deletePost(postId: bigint): Promise<void>;
    editPost(postId: bigint, text: string): Promise<PostResponse>;
    followUser(user: Principal): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getFollowers(username: string, offset: bigint, limit: bigint): Promise<PaginatedFollows>;
    getFollowing(username: string, offset: bigint, limit: bigint): Promise<PaginatedFollows>;
    getGlobalFeed(cursor: bigint | null, limit: bigint): Promise<PaginatedPosts>;
    getHomeFeed(cursor: bigint | null, limit: bigint): Promise<PaginatedPosts>;
    getNotifications(cursor: bigint | null, limit: bigint): Promise<PaginatedNotifications>;
    getPost(postId: bigint): Promise<PostResponse | null>;
    getPostsByHashtag(tag: string, cursor: bigint | null, limit: bigint): Promise<PaginatedPosts>;
    getPostsByUser(user: Principal, cursor: bigint | null, limit: bigint): Promise<PaginatedPosts>;
    getPostsByUsername(username: string, cursor: bigint | null, limit: bigint): Promise<PaginatedPosts>;
    getPrincipalByUsername(username: string): Promise<Principal | null>;
    getProfile(): Promise<UserProfile | null>;
    getProfileByUsername(username: string): Promise<UserProfileResponse | null>;
    getReplies(postId: bigint, cursor: bigint | null, limit: bigint): Promise<PaginatedPosts>;
    getTrendingHashtags(limit: bigint): Promise<Array<TrendingHashtag>>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfileResponse | null>;
    isCallerAdmin(): Promise<boolean>;
    likePost(postId: bigint): Promise<void>;
    markAllNotificationsRead(): Promise<void>;
    markNotificationRead(notifId: bigint): Promise<void>;
    muteUser(user: Principal): Promise<void>;
    quotePost(postId: bigint, text: string, mediaHash: ExternalBlob | null, mediaType: string | null): Promise<PostResponse>;
    repostPost(postId: bigint): Promise<PostResponse>;
    searchPosts(searchText: string, cursor: bigint | null, limit: bigint): Promise<PaginatedPosts>;
    searchUsers(searchText: string, limit: bigint): Promise<Array<UserProfileResponse>>;
    setProfile(username: string, displayName: string, bio: string): Promise<void>;
    unblockUser(user: Principal): Promise<void>;
    undoRepost(postId: bigint): Promise<void>;
    unfollowUser(user: Principal): Promise<void>;
    unlikePost(postId: bigint): Promise<void>;
    unmuteUser(user: Principal): Promise<void>;
    updateHeaderImage(imageHash: ExternalBlob | null): Promise<void>;
    updateProfilePicture(pictureHash: ExternalBlob | null): Promise<void>;
}
import type { Error as _Error, ExternalBlob as _ExternalBlob, FollowUserResponse as _FollowUserResponse, Notification as _Notification, NotificationType as _NotificationType, PaginatedFollows as _PaginatedFollows, PaginatedNotifications as _PaginatedNotifications, PaginatedPosts as _PaginatedPosts, PostResponse as _PostResponse, PostType as _PostType, Result as _Result, Time as _Time, UserProfile as _UserProfile, UserProfileResponse as _UserProfileResponse, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async checkUsernameAvailability(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkUsernameAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkUsernameAvailability(arg0);
            return result;
        }
    }
    async createPost(arg0: string, arg1: ExternalBlob | null, arg2: string | null): Promise<PostResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2));
                return from_candid_PostResponse_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2));
            return from_candid_PostResponse_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createReply(arg0: bigint, arg1: string, arg2: ExternalBlob | null, arg3: string | null): Promise<PostResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createReply(arg0, arg1, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3));
                return from_candid_PostResponse_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReply(arg0, arg1, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3));
            return from_candid_PostResponse_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async editPost(arg0: bigint, arg1: string): Promise<PostResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.editPost(arg0, arg1);
                return from_candid_PostResponse_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPost(arg0, arg1);
            return from_candid_PostResponse_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowers(arg0: string, arg1: bigint, arg2: bigint): Promise<PaginatedFollows> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0, arg1, arg2);
                return from_candid_PaginatedFollows_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0, arg1, arg2);
            return from_candid_PaginatedFollows_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowing(arg0: string, arg1: bigint, arg2: bigint): Promise<PaginatedFollows> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing(arg0, arg1, arg2);
                return from_candid_PaginatedFollows_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing(arg0, arg1, arg2);
            return from_candid_PaginatedFollows_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlobalFeed(arg0: bigint | null, arg1: bigint): Promise<PaginatedPosts> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalFeed(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_PaginatedPosts_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalFeed(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_PaginatedPosts_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHomeFeed(arg0: bigint | null, arg1: bigint): Promise<PaginatedPosts> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeFeed(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_PaginatedPosts_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeFeed(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_PaginatedPosts_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: bigint | null, arg1: bigint): Promise<PaginatedNotifications> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_PaginatedNotifications_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_PaginatedNotifications_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: bigint): Promise<PostResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostsByHashtag(arg0: string, arg1: bigint | null, arg2: bigint): Promise<PaginatedPosts> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByHashtag(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_PaginatedPosts_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByHashtag(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_PaginatedPosts_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostsByUser(arg0: Principal, arg1: bigint | null, arg2: bigint): Promise<PaginatedPosts> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByUser(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_PaginatedPosts_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByUser(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_PaginatedPosts_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostsByUsername(arg0: string, arg1: bigint | null, arg2: bigint): Promise<PaginatedPosts> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByUsername(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_PaginatedPosts_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByUsername(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_PaginatedPosts_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrincipalByUsername(arg0: string): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrincipalByUsername(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrincipalByUsername(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfileByUsername(arg0: string): Promise<UserProfileResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileByUsername(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileByUsername(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReplies(arg0: bigint, arg1: bigint | null, arg2: bigint): Promise<PaginatedPosts> {
        if (this.processError) {
            try {
                const result = await this.actor.getReplies(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_PaginatedPosts_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReplies(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_PaginatedPosts_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrendingHashtags(arg0: bigint): Promise<Array<TrendingHashtag>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrendingHashtags(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrendingHashtags(arg0);
            return result;
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfileResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async likePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async muteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.muteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.muteUser(arg0);
            return result;
        }
    }
    async quotePost(arg0: bigint, arg1: string, arg2: ExternalBlob | null, arg3: string | null): Promise<PostResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.quotePost(arg0, arg1, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3));
                return from_candid_PostResponse_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.quotePost(arg0, arg1, await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3));
            return from_candid_PostResponse_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async repostPost(arg0: bigint): Promise<PostResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.repostPost(arg0);
                return from_candid_PostResponse_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.repostPost(arg0);
            return from_candid_PostResponse_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchPosts(arg0: string, arg1: bigint | null, arg2: bigint): Promise<PaginatedPosts> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPosts(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_PaginatedPosts_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPosts(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_PaginatedPosts_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchUsers(arg0: string, arg1: bigint): Promise<Array<UserProfileResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0, arg1);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0, arg1);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async setProfile(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async unblockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async undoRepost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.undoRepost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.undoRepost(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async unlikePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async unmuteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unmuteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unmuteUser(arg0);
            return result;
        }
    }
    async updateHeaderImage(arg0: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHeaderImage(await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHeaderImage(await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProfilePicture(arg0: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfilePicture(await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfilePicture(await to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FollowUserResponse_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowUserResponse): Promise<FollowUserResponse> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_PaginatedFollows_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedFollows): Promise<PaginatedFollows> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedNotifications_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedNotifications): PaginatedNotifications {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_PaginatedPosts_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedPosts): Promise<PaginatedPosts> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_PostResponse_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostResponse): Promise<PostResponse> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PostType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostType): PostType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfileResponse_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileResponse): Promise<UserProfileResponse> {
    return await from_candid_record_n50(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PostResponse]): Promise<PostResponse | null> {
    return value.length === 0 ? null : await from_candid_PostResponse_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n46(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileResponse]): Promise<UserProfileResponse | null> {
    return value.length === 0 ? null : await from_candid_UserProfileResponse_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    postType: _PostType;
    authorUsername: string;
    likeCount: bigint;
    isRepostedByCurrentUser: boolean;
    authorProfilePictureHash: [] | [_ExternalBlob];
    repostCount: bigint;
    createdAt: _Time;
    text: string;
    author: Principal;
    mediaHash: [] | [_ExternalBlob];
    replyCount: bigint;
    mediaType: [] | [string];
    editedAt: [] | [_Time];
    authorDisplayName: string;
    isLikedByCurrentUser: boolean;
}): Promise<{
    id: bigint;
    postType: PostType;
    authorUsername: string;
    likeCount: bigint;
    isRepostedByCurrentUser: boolean;
    authorProfilePictureHash?: ExternalBlob;
    repostCount: bigint;
    createdAt: Time;
    text: string;
    author: Principal;
    mediaHash?: ExternalBlob;
    replyCount: bigint;
    mediaType?: string;
    editedAt?: Time;
    authorDisplayName: string;
    isLikedByCurrentUser: boolean;
}> {
    return {
        id: value.id,
        postType: from_candid_PostType_n19(_uploadFile, _downloadFile, value.postType),
        authorUsername: value.authorUsername,
        likeCount: value.likeCount,
        isRepostedByCurrentUser: value.isRepostedByCurrentUser,
        authorProfilePictureHash: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.authorProfilePictureHash)),
        repostCount: value.repostCount,
        createdAt: value.createdAt,
        text: value.text,
        author: value.author,
        mediaHash: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.mediaHash)),
        replyCount: value.replyCount,
        mediaType: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.mediaType)),
        editedAt: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.editedAt)),
        authorDisplayName: value.authorDisplayName,
        isLikedByCurrentUser: value.isLikedByCurrentUser
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nextOffset: [] | [bigint];
    hasMore: boolean;
    users: Array<_FollowUserResponse>;
}): Promise<{
    nextOffset?: bigint;
    hasMore: boolean;
    users: Array<FollowUserResponse>;
}> {
    return {
        nextOffset: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.nextOffset)),
        hasMore: value.hasMore,
        users: await from_candid_vec_n29(_uploadFile, _downloadFile, value.users)
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    username: string;
    displayName: string;
    profilePictureHash: [] | [_ExternalBlob];
}): Promise<{
    principal: Principal;
    username: string;
    displayName: string;
    profilePictureHash?: ExternalBlob;
}> {
    return {
        principal: value.principal,
        username: value.username,
        displayName: value.displayName,
        profilePictureHash: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.profilePictureHash))
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    posts: Array<_PostResponse>;
    nextCursor: [] | [bigint];
}): Promise<{
    hasMore: boolean;
    posts: Array<PostResponse>;
    nextCursor?: bigint;
}> {
    return {
        hasMore: value.hasMore,
        posts: await from_candid_vec_n35(_uploadFile, _downloadFile, value.posts),
        nextCursor: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.nextCursor))
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    notifications: Array<_Notification>;
    nextCursor: [] | [bigint];
}): {
    hasMore: boolean;
    notifications: Array<Notification>;
    nextCursor?: bigint;
} {
    return {
        hasMore: value.hasMore,
        notifications: from_candid_vec_n38(_uploadFile, _downloadFile, value.notifications),
        nextCursor: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.nextCursor))
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    notificationType: _NotificationType;
    createdAt: _Time;
    isRead: boolean;
    actorUsername: string;
    actorPrincipal: Principal;
}): {
    id: bigint;
    notificationType: NotificationType;
    createdAt: Time;
    isRead: boolean;
    actorUsername: string;
    actorPrincipal: Principal;
} {
    return {
        id: value.id,
        notificationType: from_candid_NotificationType_n41(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        isRead: value.isRead,
        actorUsername: value.actorUsername,
        actorPrincipal: value.actorPrincipal
    };
}
async function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    username: string;
    displayName: string;
    createdAt: _Time;
    updatedAt: _Time;
    headerImageHash: [] | [_ExternalBlob];
    profilePictureHash: [] | [_ExternalBlob];
}): Promise<{
    bio: string;
    username: string;
    displayName: string;
    createdAt: Time;
    updatedAt: Time;
    headerImageHash?: ExternalBlob;
    profilePictureHash?: ExternalBlob;
}> {
    return {
        bio: value.bio,
        username: value.username,
        displayName: value.displayName,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        headerImageHash: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.headerImageHash)),
        profilePictureHash: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.profilePictureHash))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    isBlockedByCurrentUser: boolean;
    principal: Principal;
    username: string;
    displayName: string;
    isMutedByCurrentUser: boolean;
    followersCount: bigint;
    createdAt: _Time;
    updatedAt: _Time;
    headerImageHash: [] | [_ExternalBlob];
    followingCount: bigint;
    isFollowedByCurrentUser: boolean;
    profilePictureHash: [] | [_ExternalBlob];
    postsCount: bigint;
}): Promise<{
    bio: string;
    isBlockedByCurrentUser: boolean;
    principal: Principal;
    username: string;
    displayName: string;
    isMutedByCurrentUser: boolean;
    followersCount: bigint;
    createdAt: Time;
    updatedAt: Time;
    headerImageHash?: ExternalBlob;
    followingCount: bigint;
    isFollowedByCurrentUser: boolean;
    profilePictureHash?: ExternalBlob;
    postsCount: bigint;
}> {
    return {
        bio: value.bio,
        isBlockedByCurrentUser: value.isBlockedByCurrentUser,
        principal: value.principal,
        username: value.username,
        displayName: value.displayName,
        isMutedByCurrentUser: value.isMutedByCurrentUser,
        followersCount: value.followersCount,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        headerImageHash: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.headerImageHash)),
        followingCount: value.followingCount,
        isFollowedByCurrentUser: value.isFollowedByCurrentUser,
        profilePictureHash: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.profilePictureHash)),
        postsCount: value.postsCount
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    repost: bigint;
} | {
    quote: bigint;
} | {
    original: null;
} | {
    reply: bigint;
}): {
    __kind__: "repost";
    repost: bigint;
} | {
    __kind__: "quote";
    quote: bigint;
} | {
    __kind__: "original";
    original: null;
} | {
    __kind__: "reply";
    reply: bigint;
} {
    return "repost" in value ? {
        __kind__: "repost",
        repost: value.repost
    } : "quote" in value ? {
        __kind__: "quote",
        quote: value.quote
    } : "original" in value ? {
        __kind__: "original",
        original: value.original
    } : "reply" in value ? {
        __kind__: "reply",
        reply: value.reply
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    repost: bigint;
} | {
    like: bigint;
} | {
    quote: bigint;
} | {
    mention: bigint;
} | {
    reply: bigint;
} | {
    follow: null;
}): {
    __kind__: "repost";
    repost: bigint;
} | {
    __kind__: "like";
    like: bigint;
} | {
    __kind__: "quote";
    quote: bigint;
} | {
    __kind__: "mention";
    mention: bigint;
} | {
    __kind__: "reply";
    reply: bigint;
} | {
    __kind__: "follow";
    follow: null;
} {
    return "repost" in value ? {
        __kind__: "repost",
        repost: value.repost
    } : "like" in value ? {
        __kind__: "like",
        like: value.like
    } : "quote" in value ? {
        __kind__: "quote",
        quote: value.quote
    } : "mention" in value ? {
        __kind__: "mention",
        mention: value.mention
    } : "reply" in value ? {
        __kind__: "reply",
        reply: value.reply
    } : "follow" in value ? {
        __kind__: "follow",
        follow: value.follow
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FollowUserResponse>): Promise<Array<FollowUserResponse>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FollowUserResponse_n30(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PostResponse>): Promise<Array<PostResponse>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PostResponse_n17(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n39(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfileResponse>): Promise<Array<UserProfileResponse>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfileResponse_n49(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
